# Generated by Django 4.2 on 2025-08-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='booking_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='details_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('fa-file-alt', 'Document'), ('fa-pencil-alt', 'Pencil'), ('fa-chart-line', 'Chart'), ('fa-briefcase', 'Briefcase'), ('fa-graduation-cap', 'Graduation Cap'), ('fa-users', 'Users'), ('fa-lightbulb', 'Lightbulb'), ('fa-rocket', 'Rocket'), ('fa-star', 'Star'), ('fa-trophy', 'Trophy'), ('fa-certificate', 'Certificate'), ('fa-award', 'Award')], help_text='Select an icon for the service', max_length=100),
        ),
    ]
