# Generated by Django 4.2 on 2025-08-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers_app', '0002_service_booking_url_service_details_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='details_url',
            field=models.CharField(blank=True, help_text="URL name for Learn More button (e.g., 'linkedin_service', 'services')", max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('fa-file-alt', 'Basic Document'), ('fa-file-image', 'Visual/Infographic CV'), ('fa-file-invoice', 'Professional CV'), ('fa-chart-line', 'Infographic Elements'), ('fa-palette', 'Visual Design'), ('fa-briefcase', 'Job/Career'), ('fa-search', 'Job Search'), ('fa-bullseye', 'Job Target'), ('fa-handshake', 'Job Offer'), ('fa-map-signs', 'Career Path'), ('fa-graduation-cap', 'Academic'), ('fa-university', 'University'), ('fa-book', 'Statement of Purpose'), ('fa-envelope-open-text', 'Letter of Recommendation'), ('fa-award', 'Achievements'), ('fab fa-linkedin', 'LinkedIn'), ('fas fa-user-tie', 'Professional Profile'), ('fas fa-network-wired', 'Professional Network'), ('fas fa-share-alt', 'Social Presence'), ('fas fa-project-diagram', 'Network Growth'), ('fa-certificate', 'Certifications'), ('fa-star', 'Excellence'), ('fa-trophy', 'Achievements'), ('fa-medal', 'Awards'), ('fa-crown', 'Premium Quality'), ('fa-rocket', 'Career Launch'), ('fa-lightbulb', 'Innovation')], help_text='Select an icon for the service', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
