# Generated by Django 4.2 on 2025-08-08 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writers_app', '0003_alter_service_details_url_alter_service_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(default='fas fa-folder', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sample Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sample_type', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('standalone', 'Standalone')], default='standalone', max_length=20)),
                ('thumbnail', models.ImageField(help_text='Recommended size: 400x500px', upload_to='samples/thumbnails/')),
                ('full_image', models.ImageField(help_text='High resolution image', upload_to='samples/full/')),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='writers_app.samplecategory')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
