# Generated by Django 4.2 on 2025-08-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers_app', '0004_samplecategory_resumesample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumesample',
            name='full_image',
        ),
        migrations.RemoveField(
            model_name='resumesample',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='resumesample',
            name='image',
            field=models.ImageField(default=1, help_text='A4 ratio image (210x297mm or 595x842px)', upload_to='samples/'),
            preserve_default=False,
        ),
    ]
