# Generated by Django 4.2 on 2025-08-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers_app', '0005_remove_resumesample_full_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumesample',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resumesample',
            name='tags',
        ),
    ]
